version: "3"

services:
  app:
    image: market-app
    entrypoint: ["go", "run", "main.go", "http"]
    ports:
      - '8080:8080'

  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local:1.16.0
    command: [ "-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory" ]
    expose:
      - "8000"
    ports:
      - '8000:8000'
