version: "3"

services:

  app:
    build: .
    container_name: app
    command: ["go", "run", "main.go", "http"]
    volumes:
      - .:/go/src/market-app
    ports:
      - '8080:8080'
    depends_on:
      - logstash

  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local:1.16.0
    command: [ "-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory" ]
    expose:
      - "8000"
    ports:
      - '8000:8000'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - http.host=0.0.0.0
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300

  kib01:
    image: docker.elastic.co/kibana/kibana:7.13.4
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'

  logstash:
    image: docker.elastic.co/logstash/logstash:7.13.4
    container_name: logstash
    ports:
      - '12201:12201/udp'
    volumes:
    - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf